In [1]:
from os import listdir
from os.path import isfile, join

# 아래 코드를 사용하여 폴더에 존재하는 파일의 이름만을 저장합니다.
mypath = './docs/'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

total_docs = []
for file in onlyfiles:
    file_path = mypath+file
    with open(file_path, 'r', encoding='utf8') as f:
        content = f.read()
    total_docs.append(content)

In [2]:
len(total_docs)

4

In [3]:
total_docs[0]

'Smartphones are by our sides, on our desks, in our pockets and bags all day long. We use them for hours every day (as the latest software on iPhone and Android phones reveals in all-too-clear detail).\nSo, it’s no surprise that battery anxiety, that great malady of the twenty-first century, is more perniciously present than ever.\n\nThe latest iPhones, I’d venture, have great battery life. I favor the iPhone XS Max and, as I’ve mentioned before, I’ve never had an issue with the battery running out, nor with the iPhone XR which, after all, has the largest battery of any iPhone. But how about the iPhone XS, the smallest-screened of the 2018 iPhones? Again, I haven’t had an issue except on those extra-long days, like flying west from London to California, for instance. On those 32-hour days caused by the time difference, the iPhone XS has struggled.\nSo, that was the Smart Battery Case I plumped for, to see if it could banish battery anxiety altogether. The essentials of this review appl

In [4]:
total_docs[-1]

'Four times, Serena Williams was only one point — a single point — from closing out a victory in the Australian Open quarterfinals.\n\nOn the first such chance, at 5-1, 40-30 in the third set, she turned her left ankle awkwardly. The owner of the best serve in the sport would lose every point she served the rest of the way.\n\nAnd so it was that a startling reversal and result would follow Wednesday at Melbourne Park, with Williams dropping the last six games of a 6-4, 4-6, 7-5 loss to No. 7-seeded Karolina Pliskova of the Czech Republic.\n\n"I can\'t say that I choked on those match points," Williams said. "She literally played her best tennis ever on those shots."\nThe 37-year-old American didn\'t call for a trainer during the match and later wouldn\'t blame the ankle for the way everything changed down the stretch, saying afterward that it "seems to be fine."\n\nBut instead of Williams moving closer to an eighth championship at the Australian Open and record-tying 24th Grand Slam ti

In [5]:
import preprocessing # import a python file for English text preprocessing

In [6]:
# 사용자 정의 불용어 사전
stopwords = ['be', 'today', 'yesterday', 'tomorrow'] 

In [7]:
# 각 문서의 전처리
# 전처리의 결과물은 불용어가 제거된 명사 단어들
docs_nouns = [preprocessing.En_preprocessing(doc, stopwords) for doc in total_docs]

In [8]:
len(docs_nouns)

4

In [9]:
print(docs_nouns[0])

['smartphones', 'side', 'desk', 'pocket', 'bag', 'day', 'hour', 'day', 'software', 'iphone', 'phone', 'reveals', 'detail', 'surprise', 'battery', 'anxiety', 'malady', 'century', 'iphones', 'venture', 'battery', 'life', 'iphone', 'x', 'max', 'issue', 'battery', 'iphone', 'xr', 'battery', 'iphone', 'iphone', 'iphones', 'havent', 'issue', 'day', 'london', 'instance', 'day', 'time', 'difference', 'iphone', 'x', 'battery', 'case', 'battery', 'anxiety', 'essential', 'review', 'iphone', 'x', 'max', 'iphone', 'xr', 'iphone', 'x', 'moment', 'packaging', 'plate', 'case', 'place', 'product', 'attention', 'everything', 'material', 'iphone', 'x', 'part', 'case', 'degree', 'iphone', 'top', 'case', 'microfibre', 'lightning', 'connector', 'base', 'case', 'lightweight', 'phone', 'thicker', 'trade', 'peace', 'mind', 'phone', 'wont', 'juice', 'design', 'apple', 'battery', 'case', 'battery', 'bulge', 'middle', 'back', 'back', 'camera', 'unit', 'bottom', 'lot', 'battery', 'board', 'hand', 'trouser', 'pocke

In [10]:
documents_filtered = [' '.join(doc) for doc in docs_nouns]

In [11]:
documents_filtered[0]

'smartphones side desk pocket bag day hour day software iphone phone reveals detail surprise battery anxiety malady century iphones venture battery life iphone x max issue battery iphone xr battery iphone iphone iphones havent issue day london instance day time difference iphone x battery case battery anxiety essential review iphone x max iphone xr iphone x moment packaging plate case place product attention everything material iphone x part case degree iphone top case microfibre lightning connector base case lightweight phone thicker trade peace mind phone wont juice design apple battery case battery bulge middle back back camera unit bottom lot battery board hand trouser pocket instance silicone feel touch smartphones surface matter back surprise fit button pressure phone switch phone ringtone fingernail hole bottom edge course match grille base iphone'

## CountVectorizer 클래스를 이용해서 벡터화 하기

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
tf_vectorizer = CountVectorizer(min_df=1, max_df=0.8, ngram_range=(1,1))
DTM_tf = tf_vectorizer.fit_transform(documents_filtered)

In [13]:
# numpy의 array 형태로 변환
import numpy as np
DTM_TF = np.array(DTM_tf.todense())

In [14]:
DTM_TF

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 0, 1],
       [0, 2, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [15]:
DTM_TF.shape

(4, 285)

In [16]:
DTM_TF[0]

array([ 0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  0,  1,  0,  3,  1,
        2,  0,  0,  0,  9,  0,  0,  1,  0,  2,  0,  1,  1,  0,  0,  1,  0,
        0,  0,  0,  6,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  4,  0,  1,  0,  1,  1,  1,
        0,  1,  0,  0,  1,  0,  1,  1,  0,  0,  0,  1,  0,  1,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  1,  0,  0,  1,  0,
        1,  0,  0,  0,  2,  0, 12,  2,  2,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1,  1,  1,  0,  1,  0,  0,  0,  1,  0,  1,  0,
        0,  0,  1,  1,  1,  0,  2,  0,  0,  1,  1,  0,  1,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,
        1,  0,  0,  0,  0,  0,  5,  0,  0,  1,  1,  0,  2,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  0

In [17]:
print(np.linalg.norm(DTM_TF[1]-DTM_TF[0])) # 첫 번째 문서와 두 번째 문서 간의 유클리디안 거리
print(np.linalg.norm(DTM_TF[2]-DTM_TF[0])) # 첫 번째 문서와 세 번째 문서 간의 유클리디안 거리
print(np.linalg.norm(DTM_TF[3]-DTM_TF[0])) # 첫 번째 문서와 네 번째 문서 간의 유클리디안 거리

23.895606290697042
24.919871588754223
25.826343140289914


In [18]:
print(np.dot(DTM_TF[0],DTM_TF[1])/(np.linalg.norm(DTM_TF[0])*np.linalg.norm(DTM_TF[1])))
print(np.dot(DTM_TF[0],DTM_TF[2])/(np.linalg.norm(DTM_TF[0])*np.linalg.norm(DTM_TF[2])))
print(np.dot(DTM_TF[0],DTM_TF[3])/(np.linalg.norm(DTM_TF[0])*np.linalg.norm(DTM_TF[3])))

0.5959464513198515
0.010149858103156184
0.021112128709387182


## TfidfVectorizer 클래스를 이용해서 벡터화 하기

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(min_df=1, max_df=0.8, ngram_range=(1,1))
DTM_tfidf = tfidf_vectorizer.fit_transform(documents_filtered)

In [20]:
DTM_TFIDF = np.array(DTM_tfidf.todense())

In [21]:
DTM_TFIDF[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.11685892, 0.        , 0.        ,
       0.04606646, 0.        , 0.        , 0.05842946, 0.        ,
       0.13819937, 0.05842946, 0.11685892, 0.        , 0.        ,
       0.        , 0.41459811, 0.        , 0.        , 0.05842946,
       0.        , 0.09213291, 0.        , 0.05842946, 0.05842946,
       0.        , 0.        , 0.05842946, 0.        , 0.        ,
       0.        , 0.        , 0.27639874, 0.        , 0.        ,
       0.05842946, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05842946, 0.05842946, 0.        , 0.        , 0.        ,
       0.        , 0.18426583, 0.        , 0.04606646, 0.        ,
       0.04606646, 0.05842946, 0.05842946, 0.        , 0.05842946,
       0.        , 0.        , 0.05842946, 0.        , 0.05842

In [22]:
DTM_TFIDF.shape

(4, 285)

In [23]:
print(np.linalg.norm(DTM_TFIDF[1]-DTM_TFIDF[0])) # 첫 번째 문서와 두 번째 문서 간의 유클리디안 거리
print(np.linalg.norm(DTM_TFIDF[2]-DTM_TFIDF[0])) # 첫 번째 문서와 세 번째 문서 간의 유클리디안 거리
print(np.linalg.norm(DTM_TFIDF[3]-DTM_TFIDF[0])) # 첫 번째 문서와 네 번째 문서 간의 유클리디안 거리

0.9538556951497862
1.409374356422095
1.4028109418615884


In [24]:
print(np.dot(DTM_TFIDF[0],DTM_TFIDF[1])/(np.linalg.norm(DTM_TFIDF[0])*np.linalg.norm(DTM_TFIDF[1])))
print(np.dot(DTM_TFIDF[0],DTM_TFIDF[2])/(np.linalg.norm(DTM_TFIDF[0])*np.linalg.norm(DTM_TFIDF[2])))
print(np.dot(DTM_TFIDF[0],DTM_TFIDF[3])/(np.linalg.norm(DTM_TFIDF[0])*np.linalg.norm(DTM_TFIDF[3])))

0.5450796564151593
0.006831961729902576
0.01606073069670202
