In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
A = np.array([[5,1],
              [3,3]])

In [3]:
eigVals, eigVecs = np.linalg.eig(A)

In [4]:
eigVals

array([6., 2.])

In [5]:
eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [6]:
v1 = eigVecs[:, 0]
v2 = eigVecs[:, 1]

In [7]:
v1

array([0.70710678, 0.70710678])

In [8]:
np.linalg.norm(v1)

0.9999999999999999

In [9]:
v2

array([-0.31622777,  0.9486833 ])

In [10]:
np.linalg.norm(v2)

0.9999999999999999

In [11]:
np.dot(A, v1)

array([4.24264069, 4.24264069])

In [12]:
eigVals[0]*v1

array([4.24264069, 4.24264069])

In [11]:
L = np.diag(eigVals)

In [12]:
L

array([[6., 0.],
       [0., 2.]])

In [13]:
np.dot(np.dot(eigVecs,L),np.linalg.inv(eigVecs))

array([[5., 1.],
       [3., 3.]])