In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
X = np.array([[7, 2],
             [3, 4],
             [5, 3]])

In [3]:
U,sing_values,VT=np.linalg.svd(X)

In [4]:
U

array([[-0.69366543,  0.59343205, -0.40824829],
       [-0.4427092 , -0.79833696, -0.40824829],
       [-0.56818732, -0.10245245,  0.81649658]])

In [5]:
sing_values

array([10.25142677,  2.62835484])

In [6]:
VT

array([[-0.88033817, -0.47434662],
       [ 0.47434662, -0.88033817]])

In [7]:
np.linalg.eig(np.dot(X,X.T))

(array([105.09175083,   6.90824917,  -0.        ]),
 array([[-0.69366543, -0.59343205, -0.40824829],
        [-0.4427092 ,  0.79833696, -0.40824829],
        [-0.56818732,  0.10245245,  0.81649658]]))

In [20]:
np.linalg.eig(np.dot(X,X.T))[1]

array([[-0.69366543, -0.59343205, -0.40824829],
       [-0.4427092 ,  0.79833696, -0.40824829],
       [-0.56818732,  0.10245245,  0.81649658]])

In [21]:
np.linalg.eig(np.dot(X.T,X))[1].T

array([[ 0.88033817,  0.47434662],
       [-0.47434662,  0.88033817]])

In [9]:
D = np.zeros((3, 2)) # 3x2의 영 행렬 생성
np.fill_diagonal(D, sing_values)

In [10]:
D

array([[10.25142677,  0.        ],
       [ 0.        ,  2.62835484],
       [ 0.        ,  0.        ]])

In [11]:
np.dot(np.dot(U,D),VT)

array([[7., 2.],
       [3., 4.],
       [5., 3.]])

축소형 확인해 보기

In [12]:
U1,sing_values1,VT1=np.linalg.svd(X, full_matrices=False)

In [13]:
U1

array([[-0.69366543,  0.59343205],
       [-0.4427092 , -0.79833696],
       [-0.56818732, -0.10245245]])

In [14]:
U

array([[-0.69366543,  0.59343205, -0.40824829],
       [-0.4427092 , -0.79833696, -0.40824829],
       [-0.56818732, -0.10245245,  0.81649658]])

In [15]:
sing_values1

array([10.25142677,  2.62835484])

In [16]:
VT1

array([[-0.88033817, -0.47434662],
       [ 0.47434662, -0.88033817]])

In [17]:
D1 = np.zeros((2, 2)) # 2x2의 영 행렬 생성
np.fill_diagonal(D1, sing_values1)

In [18]:
np.dot(np.dot(U1,D1),VT1)

array([[7., 2.],
       [3., 4.],
       [5., 3.]])