In [1]:
import numpy as np # numpy를 사용해서 벡터와 행렬 생성

In [2]:
# 행렬 생성하기
A = np.array([[1, 2],
              [3, 4]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
A.shape

(2, 2)

In [5]:
A[:, 0] # 첫 번째 열 추출

array([1, 3])

In [6]:
A[:, 1]

array([2, 4])

### 행렬과 스칼라의 연산

In [7]:
A+1

array([[2, 3],
       [4, 5]])

In [8]:
A*3

array([[ 3,  6],
       [ 9, 12]])

### 행렬 간의 연산

행렬 간 곱하기

In [9]:
B = np.array([[1,2,3],
             [4,5,6]])

In [10]:
np.dot(A, B) # 행렬 A와 B의 곱하기 연산

array([[ 9, 12, 15],
       [19, 26, 33]])

In [11]:
np.dot(B,A)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

행렬 간의 합

In [12]:
C = np.array([[2, 2],
              [4, 4]])

In [13]:
A+C

array([[3, 4],
       [7, 8]])

In [14]:
A+B

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### 행렬과 벡터 간의 연산

In [15]:
v = np.array([1,2])

행렬과 벡터의 곱하기

In [16]:
np.dot(A,v)

array([ 5, 11])

행렬과 벡터의 합

In [24]:
A+v

array([[2, 3],
       [5, 6]])

### 행렬의 종류

대각행렬

In [25]:
D = np.array([[1,0],
             [0,4]])

In [27]:
np.dot(D,D)

array([[ 1,  0],
       [ 0, 16]])

단위행렬

In [14]:
I = np.eye(2)

In [15]:
I

array([[1., 0.],
       [0., 1.]])

In [16]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.]])

In [17]:
np.dot(A,I)

array([[1., 2.],
       [3., 4.]])

전치행렬

In [13]:
A

array([[1, 2],
       [3, 4]])

In [14]:
A.T

array([[1, 3],
       [2, 4]])

In [20]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
B.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 역행렬 구하기

In [15]:
A = np.array([[1, 2],
              [2, 5]])

In [16]:
A

array([[1, 2],
       [2, 5]])

In [20]:
A_inv = np.linalg.inv(A)

In [21]:
A_inv

array([[ 5., -2.],
       [-2.,  1.]])

In [22]:
np.dot(A, A_inv)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.dot(A_inv,A)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.linalg.det(A) # determinant (행렬식)

1.0

역행렬의 기하학적 의미

In [24]:
x=np.array([1,0])

In [25]:
np.dot(A,x)

array([1, 2])

In [23]:
y = np.array([1,2])

In [24]:
np.dot(A_inv,y)

array([1., 0.])

## Rank 구하기

In [25]:
A = np.array([[1, 2],
              [2, 5]])

In [26]:
np.linalg.matrix_rank(A)

2

In [35]:
B = np.array([[1, 2],
             [2, 4]])

In [36]:
np.linalg.matrix_rank(B)

1

In [37]:
np.linalg.inv(B)

LinAlgError: Singular matrix

In [30]:
A

array([[1, 2],
       [2, 5]])

행렬식 구하기

In [31]:
np.linalg.det(A) # = 1*5 – 2*2 = 1

1.0

In [38]:
B

array([[1, 2],
       [2, 4]])

In [39]:
np.linalg.det(B)

0.0

역행렬을 이용해서 연립 방정식 풀기

In [30]:
A=np.array([[1, 2],
           [2, 5]])
y=np.array([1,2])

In [31]:
x = np.dot(np.linalg.inv(A), y)

In [32]:
x

array([1., 0.])